services:
  server:
    build: .
    image: rogueserver:latest
    restart: unless-stopped
    environment:
      debug: "true"
      #dbaddr: 117.16.44.113
      dbaddr: 192.168.1.101
      dbuser: pokerogue
      dbpass: pokerogue
      dbname: pokeroguedb
      gameurl: http://localhost:8000
      callbackurl: http://localhost:8001
      #REDIS_ADDR: 117.16.44.113:6379
      REDIS_ADDR: 192.168.1.101:6379
      REDIS_PASS: ""
      REDIS_DB:   "0"
    ports:
      - "8001:8001"
      # pprof 포트를 호스트에 노출
      - "6060:6060"

  # 시스템 메트릭 수집을 위한 Node Exporter 서비스
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    network_mode: "host"
    # node_exporter가 호스트 시스템의 정보를 읽을 수 있도록 PID와 경로를 공유합니다.
    pid: "host"
    volumes:
      - /:/host:ro,rslave
    # node_exporter가 호스트의 파일 시스템을 기준으로 정보를 수집하도록 설정합니다.
    command:
      - '--path.rootfs=/host'
